# Default values for palworld.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: qmarchi/palworld
  tag: latest
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

palworld:
  tty: true
  stdin: false
  service:
    type: NodePort
    port: 8211
    #nodePort:
    annotations: {}
  args:
  env:
    - name: SKIPUPDATE
      value: "FALSE"
    - name: PGID
      value: "1000"
    - name: PUID
      value: "1000"
    - name: ROOTLESS
      value: "TRUE"
    - name: GAMEPORT
      value: "8211"
#    - STEAMUSER=anonymous
#    - STEAMPASSWORD=
#    - STEAM2FA=
#    - GAMEPLAYERS=32
#    - MULTITHREAD=TRUE

podSecurityContext:
  runAsUser: 1000
  runAsGroup: 1000

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}

persistence:
  game:
    enabled: true
    mountPath: /game
    accessMode: ReadWriteOnce
    size: 10Gi
