apiVersion: v1
kind: Service
metadata:
  name: {{ include "palworld.fullname" . }}
  labels:
{{ include "palworld.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "palworld.fullname" . }}
{{- if .Values.palworld.service.annotations }}
{{ toYaml .Values.palworld.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.palworld.service.type }}
  {{- if .Values.palworld.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.palworld.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.palworld.service.port }}
      targetPort: server
      protocol: UDP
      name: server
      {{- if .Values.palworld.service.nodePort }}
      nodePort: {{ .Values.palworld.service.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "palworld.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
