apiVersion: v1
kind: Service
metadata:
  name: {{ include "terraria.fullname" . }}
  labels:
{{ include "terraria.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "terraria.fullname" . }}
{{- if .Values.terraria.service.annotations }}
{{ toYaml .Values.terraria.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.terraria.service.type }}
  {{- if .Values.terraria.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.terraria.service.externalTrafficPolicy }}
  {{- end }}
  ports:
  - name: server
    port: {{ .Values.terraria.service.port }}
    targetPort: server
    protocol: TCP
    {{- if .Values.terraria.service.nodePort }}
    nodePort: {{ .Values.terraria.service.nodePort }}
    {{- end }}
  {{- range .Values.terraria.extraPorts }}
  {{- if and .service.enabled .service.embedded }}
  - name: {{ .name }}
    port: {{ .service.port }}
    targetPort: {{ .name }}
    {{- if .service.nodePort }}
    nodePort: {{ .service.nodePort }}
    {{- end }}
    {{- if .protocol }}
    protocol: {{ .protocol }}
    {{- else }}
    protocol: TCP
    {{- end }}
  {{- end }}
  {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "terraria.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
