{{- if and (not .Values.serverPassword.passwordSecret) (.Values.serverPassword.game_password) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "factorio-server-charts.fullname" . }}-password
  labels:
    app: {{ template "factorio-server-charts.fullname" . }}
    chart: {{ template "factorio-server-charts.fullname" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  game_password: {{.Values.serverPassword.game_password | b64enc }}
{{- end }}
