apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "core-keeper-dedicated-server.fullname" . }}
  labels:
{{ include "core-keeper-dedicated-server.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "core-keeper-dedicated-server.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "core-keeper-dedicated-server.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "core-keeper-dedicated-server.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          env:
            - name: WORLD_FILENAME
              value: {{ include "core-keeper-dedicated-server.worldfile" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          tty: {{ .Values.core-keeper-dedicated-server.tty }}
          stdin: {{ .Values.core-keeper-dedicated-server.stdin }}
          ports:
            - name: server
              containerPort: 2875
              protocol: UDP
          volumeMounts:
          - name: core-keeper-dedicated-server-data
            mountPath: /home/steam/core-keeper-data
          - name: core-keeper-dedicated-server-server
            mountPath: /home/steam/core-keeper-dedicated
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: core-keeper-dedicated-server-data
      {{- if .Values.persistence.worlds.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "core-keeper-dedicated-server.fullname" . }}-worlds
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: core-keeper-dedicated-server-server
      {{- if .Values.persistence.config.enabled }}
        persistentVolumeClaim:
          claimName: {{ template "core-keeper-dedicated-server.fullname" .  }}-config
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
