{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "core-keeper-dedicated-server.serviceAccountName" . }}
  labels:
{{ include "core-keeper-dedicated-server.labels" . | indent 4 }}
{{- end -}}
