apiVersion: v1
kind: Service
metadata:
  name: {{ include "enshrouded.fullname" . }}
  labels:
{{ include "enshrouded.labels" . | indent 4 }}
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ include "enshrouded.fullname" . }}
{{- if .Values.enshrouded.service.annotations }}
{{ toYaml .Values.enshrouded.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.enshrouded.service.type }}
  {{- if .Values.enshrouded.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.enshrouded.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.enshrouded.service.port }}
      targetPort: server
      protocol: UDP
      name: server
      {{- if .Values.enshrouded.service.nodePort }}
      nodePort: {{ .Values.enshrouded.service.nodePort }}
      {{- end }}
    - port: {{ .Values.enshrouded.query.port }}
      targetPort: query
      protocol: UDP
      name: rcon
      {{- if .Values.enshrouded.query.nodePort }}
      nodePort: {{ .Values.enshrouded.query.nodePort }}
      {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "enshrouded.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
